version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        - PORT=8080
        - DATABASE_URL=mongodb://mongo:-D5-436cD4336c-bfEEDEgdA6G-5DbFH@roundhouse.proxy.rlwy.net:12213
        - DATABASE_NAME=orders