package env

const (
	PORT                      = "PORT"
	DATABASE_URL              = "DATABASE_URL"
	DATABASE_NAME             = "DATABASE_NAME"
	CART_SERVICE_URL          = "CART_SERVICE_URL"
	NOTIFICATIONS_SERVICE_URL = "NOTIFICATIONS_SERVICE_URL"
	AUTH_SERVICE_URL          = "AUTH_SERVICE_URL"
)
