package env

const (
	PORT                      = "PORT"
	DATABASE_URL              = "DATABASE_URL"
	DATABASE_NAME             = "DATABASE_NAME"
	PRODUCTS_SERVICE_URL      = "PRODUCTS_SERVICE_URL"
	NOTIFICATIONS_SERVICE_URL = "NOTIFICATIONS_SERVICE_URL"
	AUTH_SERVICE_URL          = "AUTH_SERVICE_URL"
)
