package env

const (
	PORT                      = "PORT"
	DATABASE_URL              = "DATABASE_URL"
	DATABASE_NAME             = "DATABASE_NAME"
	CART_SERVICE_URL          = "CART_SERVICE_URL"
	NOTIFICATIONS_SERVICE_URL = "NOTIFICATIONS_SERVICE_URL"
	AUTH_SERVICE_URL          = "AUTH_SERVICE_URL"
	SWAGGER_URI               = "SWAGGER_URI"
	RABBITMQ_URL              = "RABBITMQ_URL"
	EXCHANGE_NAME             = "EXCHANGE_NAME"
	QUEUE_NAME                = "QUEUE_NAME"
)
